### ISSUE TITLE
Asset Should Default to Three Blades

### ISSUE THREAD

**Issue by muirdata** [muirdata/muir-data#327]
Sites > Site > Asset > Blades (field)

Make Blades field default to three blades when an Asset is being created.

![adsafasdfasdf](https://cloud.githubusercontent.com/assets/2980580/23865834/2ae53b54-07d4-11e7-8430-9d16c22bbde4.png)

**Comment by JohnKJohansen-MDS** [comment]
Did this work before? I am not seeing any code Dynamic Attributes to allow the definition of a default.

**Comment by muirdata** [comment]
No, it is not a fix of a past issue. The request is an enhancement.

I did not know that defaults were not possible for the dropdowns.

**Comment by JohnKJohansen-MDS** [comment]
Added default to Dynamic Attributes

![image](https://cloud.githubusercontent.com/assets/24964880/24232411/2159fc84-0f48-11e7-8867-b714467dd9f1.png)

**Comment by JohnKJohansen-MDS** [comment]
![image](https://cloud.githubusercontent.com/assets/24964880/24232454/60e71af8-0f48-11e7-8fdb-3a8893e33585.png)

**Comment by JohnKJohansen-MDS** [comment]
![image](https://cloud.githubusercontent.com/assets/24964880/24232507/a8081612-0f48-11e7-8ea6-56ccfa5d9091.png)

**Comment by JohnKJohansen-MDS** [comment]
![image](https://cloud.githubusercontent.com/assets/24964880/24233038/9f1a80d6-0f4c-11e7-98de-3c4e70ad2f23.png)

**Comment by JohnKJohansen-MDS** [comment]
![image](https://cloud.githubusercontent.com/assets/24964880/24233052/c3d7c686-0f4c-11e7-867a-eed777a1d3d0.png)

**Comment by JohnKJohansen-MDS** [comment]
![image](https://cloud.githubusercontent.com/assets/24964880/24233073/0b70194e-0f4d-11e7-97b7-9b9321251dde.png)

**Comment by JohnKJohansen-MDS** [comment]
![image](https://cloud.githubusercontent.com/assets/24964880/24233950/97e46efc-0f52-11e7-9fae-94d9f78234ff.png)

**Comment by JohnKJohansen-MDS** [comment]
Added Defaults to Asset Types (Dynamic Attributes) such that we can now default strings, numbers and selections. In the screen shot, Manufacturer, Blades and My Mother Told Me all defaulted to the dynamic attribute defaults.

**Comment by JohnKJohansen-MDS** [comment]
Added this in last night


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: muirdata <notifications@github.com> Date: 3/22/17  9:07 PM  (GMT-08:00) To: muirdata/muir-data <muir-data@noreply.github.com> Cc: John Johansen <john@muirdata.com>, Assign <assign@noreply.github.com> Subject: Re: [muirdata/muir-data] Asset Should Default to Three Blades (#327) 
No, it is not a fix of a past issue. The request is an enhancement.
I did not know that defaults were not possible for the dropdowns.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/muirdata/muir-data","title":"muirdata/muir-data","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/muirdata/muir-data"}},"updates":{"snippets":[{"icon":"PERSON","message":"@muirdata in #327: No, it is not a fix of a past issue. The request is an enhancement.\r\n\r\nI did not know that defaults were not possible for the dropdowns."}],"action":{"name":"View Issue","url":"https://github.com/muirdata/muir-data/issues/327#issuecomment-288612052"}}}

**Comment by muirdata** [comment]
Sounds good. Will check out the default to three blades when Staging opens up.

**Comment by muirdata** [comment]
In Dev, got this working including the default of three blades.

![image](https://cloud.githubusercontent.com/assets/2980580/24327168/ef4df7f2-117e-11e7-8558-4a116854765f.png)
